::: {.hero-subsection}


# Join us

We are always interested in hearing from motivated students and researchers who want to be part of the team.


:::


## Our lab culture & team vision

In our lab, we value respect for each person’s unique personality. 
We truly acknowledge that diverse teams can be more successful. 
Based on this respect for each team member and their contributions 
to the success of our team, we appreciate the following core 
values and fill them with life:

***Team science***

We advance research together. Within the group and across collaborations. 
But not only the research itself. Team science includes also clear communication, 
mentorship and guidance. Receiving it and passing it on, so everyone can grow and flourish. 


***Curiosity***

Successful scientists are curious and ask the right questions. Finding the right 
questions might be tricky. Therefore, we value the diversity of thought, ask 
questions whenever something is unclear and re-visit old answers and paradigms 
to maybe question them (again).


***Transparency***

Transparency builds the trust in the science we do and the results we find. 
Both internally and externally. It enables us and others to reproduce our findings 
and enables us to communicate mistakes in a way we can learn from them and grow. 
Therefore, we agree on respectful and open communication.



If you see yourself conducting great science while growing with us in this environment: 
excellent! Please reach out by applying to one of the open positions or contact Pascal Mutz for more information.




## Open positions

### PhD position:

 - Find the official job ad here [Job ad PhD ResearchGate](https://www.researchgate.net/job/1038089_VP1-PhD_student_in_the_Biology_doctoral_program?utm_medium=email&utm_source=researchgate&utm_campaign=re274&loginT=H1QP4IW5MHwl40MEb6enLhbZT5PEvdKwMYchWNenGnbmMT3RipjX2SC1Flk69d3fD1dWDO8f34p9TfkjTw&pli=1&utm_term=re274_x&utm_content=re274_x_p42&cp=re274_x_p42&uid=UllJs0XEFXKScvtqJ5mDo1vmsGCo6NsiLo3P&ch=reg){.btn .btn-primary}

 - Funded for 4 years.
 
***Responsibilities:***

  - Conduct research in the field of virus evolution and virus-host interactions.  
  - Analyze virus genomics datasets using bioinformatic and computational approaches.   
  - Combine bioinformatic approaches with molecular biology experiments.  
  - Contribute to the development of research and publications in high impact journals.   
  - Present research findings at meetings and conferences.   
  - Collaborate with members of an interdisciplinary research team. 
  
  
***Qualifications and other requirements:***

***Required:***

  - Master’s degree in Bioinformatics, Computational Biology, Computer Science, Data Science, Infectious diseases, Evolutionary Biology, Biology or a related field.   
  - Strong interest in virology, primarily eukaryotic RNA viruses.  
  - Either good skills in programming/scripting languages such as Python or R OR 
  experience in molecular biology ('wet-lab') and to learn the complementary skill. At least basic understanding of bioinformatics and molecular biology required.  
  - Excellent communication and scientific writing skills.   
  - Strong written and spoken English (B2 level).
  
  
 ***Desirable:***
 
  - Prior experience in comparative genomics and phylogenetic analysis.
  - Prior experience using high-performance computing (HPC) or computational clusters.  
  - Prior experience in molecular virology techniques and studying virus-host interactions.  
  - Record of peer-reviewed publications
  
***Language in which the selection and interview process will be conducted***

  - English
 


***List of Documents Required from the Applicant (in English)***

  - Signed Consent to the processing of personal data for the purposes of the selection procedure  
  - Letter of intent  
  - Curriculum vitae

***Deadline for submitting applications: 15th August 2026***

Applications for the selection procedure with all the documents required should be sent electronically to the following address: personalni.prf@osu.cz.

To ask further questions about the position and the research project contact the Pi: pascal.mutz@gmx.de


-----

### Postdoc position

 - Find the official job ad here [Job ad Postdoc OU webpage](https://lerco.osu.eu/job-opportunitoes/?inzeratid=139){.btn .btn-primary} or here [Job ad ResearchGate](https://www.researchgate.net/job/1038066_VP1_researcher_junior_postdoc?utm_medium=email&utm_source=researchgate&utm_campaign=re274&loginT=P8nfeuY1ssziMjG8dwASxJEWpVGS2UnEf74zDLfFkmxNGc5MMUNv8voQrtTq91lWNkLrZyCNQBdzOb-JUA&pli=1&utm_term=re274_x&utm_content=re274_x_p42&cp=re274_x_p42&uid=K8QTpFbg9ghQQBMPNqzYlDb5NaswK5khHCZR&ch=reg){.btn .btn-primary}
 
 
 
 - Funded for 2 years with the opportunity for extension
 
***Responsibilities:***

  - Conduct independent research in the field of virus evolution and virus-host interactions. 
  - Analyze large-scale virus genomics datasets using bioinformatic and computational approaches.
  - Train and run large language models to predict protein interactions.
  - Contribute to the development of research projects and lead first-author publications in high impact journals. 
  - Present research findings at meetings and conferences. 
  - Collaborate with members of an interdisciplinary research team. 
  - Assist in mentoring students and junior researchers

***Qualifications and other requirements:***

***Required:***

  - PhD in Bioinformatics, Computational Biology, Computer Science, Data Science, Infectious diseases, Evolutionary Biology, or a related field. 
  - Strong computational and bioinformatic skills. 
  - Proficiency in programming/scripting languages such as Python or R. 
  - Experience using high-performance computing (HPC) or computational clusters.
  - Experience with protein language models.
  - Excellent communication and scientific writing skills. 
  - Ability to work both independently and collaboratively.
  - Track record of peer-reviewed publications.
  - Strong written and spoken English.
  - Interest in virus evolution and studying virus-host interaction. 

***Desirable:***

  - Experience in comparative genomics and phylogenetic analysis. 
  - Knowledge of RNA viruses. 
  - Experience to conduct molecular biology experiments (‘wet-lab’).
  - Knowledge of ecology-based statistics and methods.
  
***Language in which the selection and interview process will be conducted***

  - English


***List of Documents Required from the Applicant (in English)***

  - Signed Consent to the processing of personal data for the purposes of the selection procedure
  - Letter of intent
  - Curriculum vitae
  - Copy of the doctoral diploma

***Deadline for on-time applications***

  - 15th of August, 2026


Applications for the selection procedure with all the documents required should be sent electronically to the following address: personalni.prf@osu.cz.
To ask further questions about the position and the research project contact the Pi: pascal.mutz@gmx.de

-----

### Own funding?

If you are interested in joining our group and have already secured your own funding
or plan to do so: please reach out to Pascal Mutz outlining briefly your envisioned research project, why it 
contributes to our research vision and how you see yourself contributing to our team (~1 page). Also, please add a short 
CV, outline briefly the (envisioned) funding and how Pascal could help you to secure it.


 
-----

### Undergraduate and Master's Students

Projects are available throughout the year. Please contact Pasal Mutz 
directly by a short email explaining your interest in our research.


